stages:
  - test
  - secret-detection
  - mirror   # ✅ Add this

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: secret-detection

mirror_to_github:
  stage: mirror
  script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/YOUR_USERNAME/YOUR_REPO.git
    - git fetch origin main  # ensure main is present
    - git push github main   # push just the main branch
  only:
    - main