stages:
  - test
  - secret-detection
  - mirror   # ✅ Add this

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: secret-detection

mirror_to_github:
  stage: mirror
  script:
    - git config --global user.email "real.pattern.laboratory@gmail.com"
    - git config --global user.name "RealPatternLab"
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/RealPatternLab/Michael-Levin-QA-Engine
    - git fetch origin
    - git checkout -b main origin/main
    - git push --force github main  # ← force override
  only:
    - main